[package]
name = "arduino"
version = "0.1.0"
edition = "2018"

[dependencies]
arduino-hal = { git = "https://github.com/Rahix/avr-hal.git", rev = "92d540c", features = ["arduino-uno"] }
panic-halt = "0.2.0"

[profile.dev]
panic = "abort" 

[profile.release]
panic = "abort" 
